

title: Sonakshi Sharma # your name (or website title) here
baseurl: "/"
url: "https://sonashine.github.io/"

description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br><br>
  Computer Science undergraduate with a keen interest in Data Science, currently looking for a part-time job or an internship.
  <br><br>
  <a href="https://www.linkedin.com/in/sonakshisharma1298/ ">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://sonashine.github.io/projects/Bank-Loan-Approval-Using-Artificial-Neural-Nets.html">Bank Loan Approval Using Artificial Neural Nets</a>
  <br><br>
  <a href="https://sonashine.github.io/projects/Project-Predicting-stock-prices>Project Predicting stock prices</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
